### ISSUE TITLE
document pre-commit usage

### ISSUE THREAD

**Issue by aerickson** [aerickson/tf_authoritative_scanner#4]

**Comment by aerickson** [comment]
```
- repo: https://github.com/aerickson/tf_authoritative_scanner.git
  rev: v1.0.4
  hooks:
    - id: tfas
 ```
